server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: Server Discovery
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF