server:
  port: 8060
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: firstApp
        uri: http://localhost:8050/
        predicates:
        - Path=/first/**
      - id: secondApp
        uri: http://localhost:8051/
        predicates:
        - Path=/second/**
          
          