server:
  port: 0

spring:
  application:
    name: firstService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true